# Generated by Django 4.0.1 on 2022-03-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('sno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('sno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('professor_sno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.professor')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentLecture',
            fields=[
                ('sno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('student_sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.student')),
            ],
            options={
                'db_table': 'enrollment_lecture',
            },
        ),
    ]
