# Generated by Django 4.0.1 on 2022-03-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('author_seq', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.CASCADE, to='bookstore.author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
